POST http://localhost:3000/cats HTTP/1.1
content-type: application/json

{
    "name": "Banny",
    "age": true,
    "breed": "Africa1"
}

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "id": "abc",
    "firstName": "Banny",
    "lastName": "Nguyen",
    "isActive": true
}

###
POST http://localhost:3000/uploadfiles HTTP/1.1
Content-Type: multipart/form-data; boundary=----XXX

title
------XXX
Content-Disposition: form-data; name="image"; filename="anh mua thu.png"
Content-Type: image/png

< ./anh mua thu.png
------XXX--
